name: CI

on: 
  schedule:
  - cron: 0 2 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build toto1310/simple-jenkins-dood:latest --file Dockerfile --pull --no-cache .
